config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#front'
  get 'home', to: 'tasting_notes#index'

  resources :users, only: [:create]
  resources :sessions, only: [:create]
  resources :wine_types, only: [:show]
  resources :wines, except: [:delete] do
    resources :tasting_notes, only: [:new, :create, :index, :show]
  end  
    
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'
end

app/models/aroma.rb
class Aroma < ActiveRecord::Base
  has_many :tasting_note_aromas
  has_many :tasting_notes, through: :tasting_note_aromas

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  has_many :tasting_note_flavors
  has_many :tasting_notes, through: :tasting_note_flavors

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/tasting_note.rb
class TastingNote < ActiveRecord::Base
  belongs_to :user
  belongs_to :wine
  belongs_to :wine_type
  has_many :tasting_note_flavors
  has_many :flavors, -> { order("created_at") }, through: :tasting_note_flavors
  has_many :tasting_note_aromas
  has_many :aromas, -> { order("created_at") }, through: :tasting_note_aromas
  validates_presence_of :tasting_date
  validates_presence_of :quality
  validates_presence_of :comments
end

app/models/tasting_note_aroma.rb
class TastingNoteAroma < ActiveRecord::Base
  belongs_to :tasting_note
  belongs_to :aroma
end

app/models/tasting_note_flavor.rb
class TastingNoteFlavor < ActiveRecord::Base
  belongs_to :tasting_note
  belongs_to :flavor
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasting_notes, -> { order(:tasting_date) }
  
  validates_presence_of :email, :password, :full_name
  validates :email, uniqueness: true

  has_secure_password validations: false
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :wine_type
  has_many :tasting_notes

  validates_presence_of :description
  validates_presence_of :wine_type_id
  validates_uniqueness_of :description, scope: :vintage
  validates_inclusion_of :vintage, 
    in: 1945..Date.today.strftime("%Y").to_i, 
    message: "must be between 1945 and this year.",
    allow_blank: true

end

app/models/wine_type.rb
class WineType < ActiveRecord::Base
  has_many :wines
  has_many :tasting_notes
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def signed_in?
    !!current_user
  end
  
  def require_user
    if !signed_in?
      flash[:danger] = "You must be signed in."
      redirect_to sign_in_path
    end  
  end    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
    redirect_to home_path if signed_in? 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    redirect_to home_path if signed_in?  
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully signed in."
      redirect_to home_path
    else
      flash[:danger] = "Your email address and/or password are incorrect." 
      redirect_to sign_in_path
    end   
  end 

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have signed out."
    redirect_to root_path
  end 
end

app/controllers/tasting_notes_controller.rb
class TastingNotesController < ApplicationController
  before_action :require_user
  before_action :set_wine, only: [:new, :create]

  def index
    @tasting_notes = TastingNote.order(tasting_date: :desc).page(params[:page]).per(3)
  end  

  def show
    @tasting_note = TastingNote.find(params[:id])
    @wine = @tasting_note.wine
  end
    
  def new
    @tasting_note = TastingNote.new
  end  

  def create
    @tasting_note = TastingNote.new(tasting_note_params)
    @tasting_note.user = current_user
    @tasting_note.wine = @wine
    @tasting_note.wine_type = @wine.wine_type

    if @tasting_note.save
      flash[:success] = "Your tasting note has been saved."
      redirect_to home_path
    else
      render :new  
    end  
  end
  
  private

  def tasting_note_params
    params.require(:tasting_note).permit(:tasting_date, :color, :color_intensity, :clarity, :aroma_intensity, :sweetness, :acidity, :tannin, :body, :finish, :quality, :flavor_intensity, :comments, flavor_ids: [], aroma_ids: [])
  end  

  def set_wine
    @wine = Wine.find(params[:wine_id])
  end
    
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "You have successfully signed up!"
      redirect_to sign_in_path
    else
      render 'new'
    end  
  end  

  private

  def user_params
    params.require(:user).permit(:full_name, :email, :password)
  end  
end

app/controllers/wine_types_controller.rb
class WineTypesController < ApplicationController
  before_action :require_user
  
  def show
    @wine_type = WineType.find(params[:id])
    @tasting_notes = @wine_type.tasting_notes.order(tasting_date: :desc).page(params[:page]).per(3)
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :require_user

  def show
    @wine = Wine.find(params[:id])
    @tasting_notes = @wine.tasting_notes.order(tasting_date: :desc).page(params[:page]).per(3)
  end
    
  def new
    @wine = Wine.new
  end 

  def create
    @wine = Wine.new(wine_params)

    if @wine.save
      flash[:success]  = "#{@wine.vintage} #{@wine.description} has been successfully added."
      redirect_to new_wine_tasting_note_path(@wine)
    else
      render 'new'
    end
  end

  def wine_params
    params.require(:wine).permit(:description, :vintage, :wine_type_id)
  end  

end  

app/helpers/application_helper.rb
module ApplicationHelper
  def friendly_date(date) 
    date.strftime("%B %d, %Y")   
  end
end

app/views/layouts/_messages.html.erb
<div id="flash-messages">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %> 
      <div class="alert alert-<%= name %> alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert">&#215;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-items">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Tasting Notes", root_path, :class => 'navbar-brand' %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-items">
      <% if signed_in? %>
        
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle", data-toggle="dropdown", role="button", aria-haspopup="true", aria-expanded="false">Wine Types<span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% WineType.all.each do |type| %>
                <li>
                  <%= link_to type.name, wine_type_path(type) %>
                </li>  
              <% end %> 
            </ul>  
          </li> 

          <li class="dropdown">
            <a href="#" class="dropdown-toggle", data-toggle="dropdown", role="button", aria-haspopup="true", aria-expanded="false">Wines<span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% Wine.all.each do |wine| %>
                <li>
                  <%= link_to wine.vintage.to_s + ' ' + wine.description, wine_path(wine) %>
                </li>  
              <% end %>  
            </ul>  
          </li> 

          <li class="dropdown">
            <a href="#" class="dropdown-toggle", data-toggle="dropdown", role="button", aria-haspopup="true", aria-expanded="false">New Tasting Note<span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% Wine.all.each do |wine| %>
                <li>
                  <%= link_to wine.vintage.to_s + ' ' + wine.description, new_wine_tasting_note_path(wine) %>
                </li>  
              <% end %> 
              <li class="divider"></li>
              <li>
                <%= link_to new_wine_path do %>
                  <span class="glyphicon glyphicon-plus"></span>
                  new wine
                <% end %>
              </li>    
            </ul>  
          </li> 
        </ul>

        <div class="btn-group nav navbar-nav navbar-right">
            <button type="button" class="btn btn-default navbar-btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true", aria-expanded="false">
              <%= current_user.full_name %> <span class="caret"></span>
            </button>  
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to sign_out_path do %>
                  <span class="glyphicon glyphicon-log-out"></span>
                  sign out
                <% end %>  
              </li>   
            </ul>
          </div>           
      <% end %>  
    </div> 
  </div>  
</nav>   
  

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasting Notes</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <% if signed_in? %>
      <header>
        <%= render 'layouts/navigation' %>
      </header>
      <section>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div> <!--! end of .container --> 
      </section> 
    <% else %>
      <section>
        <div class="container front-container">
          <div class="row">
            <div class="col-md-12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div> 
        </div> <!--! end of .container --> 
      </section> 
    <% end %>
    <footer>
      &copy 2015 Tasting Notes
    </footer>    
  </body>
</html>

app/views/pages/front.html.erb
<div class="jumbotron col-md-8 col-md-offset-2">
  <h1>Tasting Notes</h1>
  <p>
    Keep track of the wine that you drink.
  </p>
  <p>
    <%= link_to 'Sign up', sign_up_path, class: "btn btn-default btn-lg btn-sign-up" %>
    or
    <%= link_to 'Sign in', sign_in_path, class: "btn btn-default btn-lg btn-sign-in" %>
  </p> 
</div>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
</p>
<hr/>  

app/views/shared/_errors.html.erb
<% if model_object.errors.any? %>
  <div class="alert alert-danger">
    <h5>Please fix the following errors:</h5>
    <ul>
      <% model_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>  
    </ul>
  </div>  
<% end %>    

app/views/tasting_notes/_notes_summary.html.erb
<div class="list-group">
  <% notes.each do |note| %>
    <div class="list-group-item well col-md-8">
      <div class="row">
        <span class="col-md-1 flaticon-glass-<%= note.wine_type.name %> glass-color-<%= note.wine_type.name %>"></span>
        <div class="col-md-11">
          <h4 class="list-group-item-heading"><%= link_to note.wine.vintage.to_s + ' ' + note.wine.description, wine_tasting_note_path(note.wine, note) %></h4>
          <p class="list-group-item-text">Tasted on <%= friendly_date(note.tasting_date) %> by <%= note.user.full_name %></p>
          <p class="list-group-item-text">Overall Quality: <%= note.quality %></p>
          <p class="list-group-item-text">Comments: <em>"<%= note.comments %>"</em></p> 
        </div>  
      </div>
    </div>     
  <% end %> 
</div>

<div class="row">
  <div class="col-md-8 paginator">
    <%= paginate @tasting_notes %>
  </div>
</div>
</br>    
<div class="row">
  <div class="col-md-12">Font generated by <a href="http://www.flaticon.com">flaticon.com</a>
    under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY</a>. The authors are: <a href="http://www.freepik.com">Freepik</a>, <a href="http://www.simpleicon.com">SimpleIcon</a>
  </div> 
</div>    

app/views/tasting_notes/index.html.erb
<%= render "shared/content_title", title: "All Tasting Notes" %>

<%= render "notes_summary", notes: @tasting_notes %> 

app/views/tasting_notes/new.html.erb
<%= render "shared/content_title", title: "Add a Tasting Note for #{@wine.vintage} #{@wine.description}" %>

<%= form_for [@wine, @tasting_note], html: {class: "form-horizontal tn-form"} do |f| %>
  <%= render 'shared/errors', model_object: @tasting_note %>
    
  <div class="form-group">
    <%= f.label "Tasting Date:", class: "col-md-2 tn-body-text" %>
    <%= f.date_select :tasting_date, class: "col-md-2" %>     
  </div> 

  <div class="panel panel-default tasting-note-panel">
    <div class="panel-heading panel-color-<%= @wine.wine_type.name %>">
      <h5 class="panel-title">Appearance</h5> 
    </div> 
    <div class="panel-body"> 
      <div class="form-group">
        <%= f.label :color, class: "col-md-1" %>
        <% if @wine.wine_type.name == "Red" %>
          <%= f.select(:color, [ ['purple', 'purple'], ['ruby', 'ruby'], ['garnet', 'garnet'], ['tawny', 'tawny'], ['brown', '5'] ], {include_blank: true}, {class: "col-md-2"}) %> 
        <% elsif @wine.wine_type.name == "Rose" %> 
          <%= f.select(:color, [ ['pink', 'pink'], ['salmon', 'salmon'], ['orange', 'orange'] ], {include_blank: true}, {class: "col-md-2"}) %> 
        <% else %>
          <%= f.select(:color, [ ['lemon-green', 'lemon-green'], ['lemon', 'lemon'], ['gold', 'gold'], ['amber', 'amber'], ['brown', 'brown'] ], {include_blank: true}, {class: "col-md-2"}) %> 
        <% end %>      
        <%= f.label "Intensity", class: "col-md-1" %>
        <%= f.select(:color_intensity, [ ['pale', 'pale'], ['medium', 'medium'], ['deep', 'deep'] ], {include_blank: true}, {class: "col-md-1"}) %> 
        <%= f.label :clarity, class: "col-md-1" %>
        <%= f.select(:clarity, [ ['clear', 'clear'], ['hazy', 'hazy'] ], {include_blank: true}, {class: "col-md-1"}) %> 
      </div>
    </div>  
  </div>

  <div class="panel panel-default tasting-note-panel">
    <div class="panel-heading panel-color-<%= @wine.wine_type.name %>">
      <h5 class="panel-title">Aroma</h5> 
    </div> 
    <div class="panel-body">  
      <div class="form-group">
        <%= f.label "Intensity", class: "col-md-1" %>
        <%= f.select(:aroma_intensity, [ ['light', 'light'], ['medium', 'medium'], ['pronounced', 'pronounced'] ], {include_blank: true}, {class: "col-md-1"}) %> 
        <%= f.label "Aromas:", class: "col-md-1" %>
        <%= f.collection_check_boxes(:aroma_ids, Aroma.order(:created_at), :id, :name) do |cb| %> 
          <% cb.label(class: "checkbox checkbox-inline checkbox-row") {cb.check_box + cb.text} %>  
        <% end %> 
      </div>  
    </div>
  </div>    

  <div class="panel panel-default tasting-note-panel">
    <div class="panel-heading panel-color-<%= @wine.wine_type.name %>">
      <h5 class="panel-title">Flavor</h5>
    </div>
    <div class="panel-body">  
      <div class="form-group">
        <%= f.label :sweetness, class: "col-md-1" %>
        <%= f.select(:sweetness, [ ['dry', 'dry'], ['medium-dry', 'medium-dry'], ['medium-sweet', 'medium-sweet'], ['sweet', 'sweet'], ['luscious', 'luscious'] ], {include_blank: true}, {class: "col-md-2"}) %>  
        <%= f.label :acidity, class: "col-md-1" %>
        <%= f.select(:acidity, [ ['low', 'low'], ['medium', 'medium'], ['high', 'high'] ], {include_blank: true}, {class: "col-md-1"}) %> 
        <%= f.label :tannin, class: "col-md-1" %>
        <%= f.select(:tannin, [ ['none', 'none'], ['low', 'low'], ['medium', 'medium'], ['high', 'high'] ], {include_blank: true}, {class: "col-md-1"}) %> 
        <%= f.label :body, class: "col-md-1" %>
        <%= f.select(:body, [ ['light', 'light'], ['medium', 'medium'], ['full', 'full'] ], {include_blank: true}, {class: "col-md-1"}) %> 
        <%= f.label :finish, class: "col-md-1" %>
        <%= f.select(:finish, [ ['short', 'short'], ['medium', 'medium'], ['long', 'long'] ], {include_blank: true}, {class: "col-md-1"}) %> 
      </div>
      <div class="form-group">
        <%= f.label "Intensity", class: "col-md-1" %>
        <%= f.select(:flavor_intensity, [ ['light', 'light'], ['medium', 'medium'], ['pronounced', 'pronounced'] ], {include_blank: true}, {class: "col-md-1"}) %> 
        <%= f.label "Flavors:", class: "col-md-1" %>
        <%= f.collection_check_boxes(:flavor_ids, Flavor.order(:created_at), :id, :name) do |cb| %> 
          <% cb.label(class: "checkbox checkbox-inline checkbox-row") {cb.check_box + cb.text} %>  
        <% end %>   
      </div>  
    </div>
  </div>    

  <div class="panel panel-default tasting-note-panel">
    <div class="panel-heading panel-color-<%= @wine.wine_type.name %>">
      <h5 class="panel-title">Conclusions</h5>
    </div>
    <div class="panel-body">  
      <div class="form-group">
        <%= f.label :quality, class: "col-md-1" %>
        <%= f.select(:quality, [ ['poor', 'poor'], ['acceptable', 'acceptable'], ['good', 'good'], ['very good', 'very good'], ['outstanding', 'outstanding'] ], {include_blank: true}, {class: "col-md-1"}) %> 
        <%= f.label :comments, class: "col-md-1" %>
        <%= f.text_area :comments, rows: 1, class: "col-md-7" %>
      </div>
    </div>
  </div>    
  <br/> 
  <%= f.submit "Add Tasting Note", class: "btn btn-primary" %>  
<% end %>
<br/>   

app/views/tasting_notes/show.html.erb
<%= render "shared/content_title", title: "Tasting Note for #{@wine.vintage} #{@wine.description}" %>

<div class="panel panel-default tasting-note-panel">
  <div class="panel-heading panel-color-<%= @tasting_note.wine_type.name %>">
    <h5 class="panel-title">Tasting Information</h5>
  </div>  
  <div class="panel-body">
    <div class="row">
      <p class="col-md-3"><span class="tasting-note-category-label">Tasting Date:</span> <%= friendly_date(@tasting_note.tasting_date) %></p>
      <p class="col-md-2"><span class="tasting-note-category-label">Tasted By:</span> <%= @tasting_note.user.full_name %></p> 
    </div>
  </div>
</div>            
<div class="panel panel-default tasting-note-panel">
  <div class="panel-heading panel-color-<%= @tasting_note.wine_type.name %>">
    <h5 class="panel-title">Appearance</h5> 
  </div> 
  <div class="panel-body"> 
    <div class="row">
      <p class="col-md-2"><span class="tasting-note-category-label">Color:</span> <%= @tasting_note.color %></p> 
      <p class="col-md-2"><span class="tasting-note-category-label">Intensity:</span> <%= @tasting_note.color_intensity %></p>      
      <p class="col-md-2"><span class="tasting-note-category-label">Clarity:</span> <%= @tasting_note.clarity %></p>   
    </div>
  </div>  
</div>

<div class="panel panel-default tasting-note-panel">
  <div class="panel-heading panel-color-<%= @tasting_note.wine_type.name %>">
    <h5 class="panel-title">Aroma</h5> 
  </div> 
  <div class="panel-body">  
    <div class="row">
      <p class="col-md-2"><span class="tasting-note-category-label">Intensity:</span> <%= @tasting_note.aroma_intensity %></p>
      <p class="col-md-6"><span class="tasting-note-category-label">Aromas:</span>
        <%= @tasting_note.aromas.map{|a| a.name}.join(", ") %>
      </p>     
    </div>  
  </div>
</div>    

<div class="panel panel-default tasting-note-panel">
  <div class="panel-heading panel-color-<%= @tasting_note.wine_type.name %>">
    <h5 class="panel-title">Flavor</h5>
  </div>
  <div class="panel-body">  
    <div class="row">
      <p class="col-md-3"><span class="tasting-note-category-label">Sweetness:</span> <%= @tasting_note.sweetness %></p>
      <p class="col-md-2"><span class="tasting-note-category-label">Acidity:</span> <%= @tasting_note.acidity %></p>
      <p class="col-md-2"><span class="tasting-note-category-label">Tannin:</span> <%= @tasting_note.tannin %></p>
      <p class="col-md-2"><span class="tasting-note-category-label">Body:</span> <%= @tasting_note.body %></p>
      <p class="col-md-2"><span class="tasting-note-category-label">Finish:</span> <%= @tasting_note.finish %></p>
    </div>
    <div class="row">
      <p class="col-md-2"><span class="tasting-note-category-label">Intensity:</span> <%= @tasting_note.flavor_intensity %></p>
      <p class="col-md-6"><span class="tasting-note-category-label">Flavors:</span>
        <%= @tasting_note.flavors.map{|f| f.name}.join(", ") %>
    </div>  
  </div>
</div>    

<div class="panel panel-default tasting-note-panel">
  <div class="panel-heading panel-color-<%= @tasting_note.wine_type.name %>">
    <h5 class="panel-title">Conclusions</h5>
  </div>
  <div class="panel-body">  
    <div class="row">
      <p class="col-md-3"><span class="tasting-note-category-label">Overall Quality:</span> <%= @tasting_note.quality %></p>
      <p class="col-md-8"><span class="tasting-note-category-label">Comments:</span> <%= @tasting_note.comments %></p>
    </div>
  </div>
</div> 
<br/> 
<br/>  
  

app/views/users/new.html.erb
<%= render 'shared/errors', model_object: @user %> 

<div class="col-sm-6 col-md-4 col-md-offset-4">
  <div class="panel panel-default sign-in-sign-up-panel">
    <div class="panel-heading">
      <strong>Sign up</strong>
    </div>  
    <div class="panel-body">
      <%= form_for @user do |f| %>
        <fieldset>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
              <%= f.text_field :full_name, class: "form-control", placeholder: "Full Name" %>
            </div>  
          </div>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
              <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
            </div>  
          </div>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
              <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>  
          </div>
          <br/>
          <%= f.submit value: "Sign up", class: "btn btn-lg btn-sign-up btn-block" %> 
        </fieldset>  
      <% end %>   
    </div>      
  </div>  
</div>      

app/views/wine_types/show.html.erb
<% all_tasting_notes = link_to 'All Tasting Notes', home_path %>

<%= render "shared/content_title", title: "#{all_tasting_notes} &raquo; Showing Tasting Notes for #{@wine_type.name}".html_safe %> 

<%= render '/tasting_notes/notes_summary', notes: @tasting_notes %>

app/views/wines/new.html.erb
<%= render "shared/content_title", title: "Add a New Wine" %>

<%= form_for @wine, html: {class: "form-horizontal"} do |f| %>
  <%= render 'shared/errors', model_object: @wine %>
  <div class="well">
    <div class="form-group">
      <%= f.label "Type", class: "col-md-3 tn-body-text" %>
      <div class="col-md-9">
        <%= f.collection_select :wine_type_id, WineType.all, :id, :name, prompt: true %> 
      </div>  
    </div>   
    <div class="form-group">
      <%= f.label "Description (producer, varietal, region)", class: "col-md-3 tn-body-text" %>
      <div class="col-md-9">
        <%= f.text_field :description, class: "col-md-9" %> 
      </div>    
    </div>  
    <div class="form-group">
      <%= f.label :vintage, class: "col-md-3 tn-body-text" %>
      <div class="col-md-9">
        <%= f.text_field :vintage %>
      </div>  
    </div>
  </div>  
  <br/>
    <%= f.submit "Add Wine", class: "btn btn-primary" %>  
<% end %> 

app/views/wines/show.html.erb
<% all_tasting_notes = link_to 'All Tasting Notes', home_path %>

<%= render "shared/content_title", title: "#{all_tasting_notes} &raquo; Showing Tasting Notes for #{@wine.vintage} #{@wine.description}".html_safe %> 

<%= render '/tasting_notes/notes_summary', notes: @tasting_notes %>
  